### ISSUE TITLE
Missing geysers in some maps

### ISSUE THREAD

**Issue by msikma** [ShieldBattery/bw-chk#12]
Hi there, I've been using bw-chk and scm-extractor for some personal projects, and they work extremely well. However recently I've noticed that on some maps, geysers aren't being rendered for some reason.

For example, here on Eclipse 1.2 it works perfectly:

![(2)Eclipse_1 2](https://user-images.githubusercontent.com/1507745/202700604-c135a08c-e766-40a9-9522-fbcee6c36850.jpg)

Then on Butter 1.4 there's no geysers for some reason:

![(2)Butter 1 4](https://user-images.githubusercontent.com/1507745/202700667-4caeec30-b3eb-4b5d-a7b2-ceff2fc128a4.jpg)

[I think I have all the right files](https://github.com/ShieldBattery/scm-extractor/issues/13) but maybe I'm missing some?

[My code](https://github.com/msikma/bwpreview) is pretty simple: first I use `bw-chk` to load the graphics (`Chk.fsFileAccess()`), then I pipe the contents of the map file to the `scm-extractor` main export, then I run `res.image()` with the previously loaded graphics. As far as I can tell that's how it's supposed to be done, and it seems to work fine for most maps.

I'm guessing maybe this is related to some trickery map makers do in modern maps, to perfectly position the geysers, which isn't 100% supported yet? Or am I using the library wrong in some way? I'm using the latest published versions (bw-chk 1.3.0, scm-extractor 1.0.6).

Appreciate any help you might give 🙏

edit: attaching maps for convenience:

* [(2)Butter 1.4.scx.zip](https://github.com/ShieldBattery/bw-chk/files/10041095/2.Butter.1.4.scx.zip)
* [(2)Eclipse_1.2.scx.zip](https://github.com/ShieldBattery/bw-chk/files/10041096/2.Eclipse_1.2.scx.zip)

**Comment by neivv** [comment]
You probably have non-expansion geyser graphics. The geyser graphic is unique in that it has different frame for each tileset, and so it has a 5-frame version in stardat.mpq and 8-frame version in broodat.mpq.

I'm not able to check right now which version is in SC:R casc archive (Could be the 5-frame one? Which would be annoying), but i'll attach the correct graphic (`unit/neutral/geyser.grp`)

[geyser.zip](https://github.com/ShieldBattery/bw-chk/files/10042345/geyser.zip)

Guess bw-chk could be improved too to render sprites with wrong tileset graphics if the given grp file doesn't have the needed frame.

**Comment by msikma** [comment]
I didn't realize this was still open (for almost a year) but I just wanted to mention that this resolved the issue, thanks a lot!
