### ISSUE TITLE
Extract .chk from .rep too ?

### ISSUE THREAD

**Issue by Death-cord** [ShieldBattery/bw-chk#15]
I think the .chk file is also included in the replay, so, can we have a function to extract .chk/.scm/.scx from a replay and also generate a map image from the replay, an old tool did that before, but its very buggy:
https://liquipedia.net/starcraft/ReXplorer

**Comment by tec27** [comment]
This library just parses CHK files, actually extracting those files from any particular format is out of its scope. `scm-extractor` exists to extract CHKs from SCM/SCX files, so you'd probably want to write a library (or find one) that pulls these files out of reps,  and then pass the result of that to this library.

`jssuh` provides such a thing that you could use for these purposes: https://github.com/ShieldBattery/jssuh#parserpipechkstream
